In [7]:
##Json Data
data=sqlCtx.read.json("file:///E:/Eclipse_Android_workspaces/ApacheSpark/data/fileformats/jsonInput.json")
sqlCtx.registerDataFrameAsTable(data,'jsonTable')
out=sqlCtx.sql("select * from jsonTable where string='string1'")
out.collect()

[Row(array=[1, 2, 3], dict=Row(extra_key=None, key='value1'), int=1, string='string1')]

In [17]:
##csv data
csv=sqlCtx.read.csv("file:///E:/Eclipse_Android_workspaces/ApacheSpark/data/fileformats/csvInput.csv")
outCsv=csv.filter(csv['_c0']=='ZABU')
outCsv.collect()

[Row(_c0='ZABU', _c1='N 17', _c2=None),
 Row(_c0='ZABU', _c1='M/TIO@ 6', _c2=None),
 Row(_c0='ZABU', _c1='UX 62', _c2=None),
 Row(_c0='ZABU', _c1='UX 63', _c2=None),
 Row(_c0='ZABU', _c1='X:HY 3', _c2=None),
 Row(_c0='ZABU', _c1='M/FAN 2', _c2=None),
 Row(_c0='ZABU', _c1='M/FAN 4', _c2=None),
 Row(_c0='ZABU', _c1='UX@ 12', _c2=None),
 Row(_c0='ZABU', _c1='UX 274', _c2=None),
 Row(_c0='ZABU', _c1='UX 10', _c2=None),
 Row(_c0='ZABU', _c1='X:HY 5', _c2=None),
 Row(_c0='ZABU', _c1='TM/U 1', _c2=None),
 Row(_c0='ZABU', _c1='A 256', _c2=None),
 Row(_c0='ZABU', _c1='H2 111', _c2=None),
 Row(_c0='ZABU', _c1='UX 115', _c2=None),
 Row(_c0='ZABU', _c1='UX 116', _c2=None),
 Row(_c0='ZABU', _c1='UX 275', _c2=None),
 Row(_c0='ZABU', _c1='M/TIO 17', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 11', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 12', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 28', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 29', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 -1', _c2=None),
 Row(_c0='ZABU', _c1='CA3 29', _c2=None),
 Row(_c0='ZABU', _c1='UX 354', _c2=None),
 Row(_c0='ZABU', _c1='A 118', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 10', _c2=None),
 Row(_c0='ZABU', _c1='WCA@ 3', _c2=None),
 Row(_c0='ZABU', _c1='UX@ 7', _c2=None),
 Row(_c0='ZABU', _c1='A 257', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 17', _c2=None),
 Row(_c0='ZABU', _c1='AT 12', _c2=None),
 Row(_c0='ZABU', _c1='ASM 57', _c2=None),
 Row(_c0='ZABU', _c1='CA3 31', _c2=None),
 Row(_c0='ZABU', _c1='SENSM 14', _c2=None),
 Row(_c0='ZABU', _c1='SENSM 13', _c2=None),
 Row(_c0='ZABU', _c1='CX 22/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 6', _c2=None),
 Row(_c0='ZABU', _c1="KZ '97", _c2=None),
 Row(_c0='ZABU', _c1='DD 12', _c2=None),
 Row(_c0='ZABU', _c1='DD 13', _c2=None),
 Row(_c0='ZABU', _c1='DD 14', _c2=None),
 Row(_c0='ZABU', _c1='DD 24', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 8', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 19', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 20', _c2=None),
 Row(_c0='ZABU', _c1='AT 2', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 11', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 3', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 4', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 5', _c2=None),
 Row(_c0='ZABU', _c1='IM 202', _c2=None),
 Row(_c0='ZABU', _c1='AT 17', _c2=None),
 Row(_c0='ZABU', _c1='AT 18', _c2=None),
 Row(_c0='ZABU', _c1='AT 19', _c2=None),
 Row(_c0='ZABU', _c1='AT 20', _c2=None),
 Row(_c0='ZABU', _c1='AT 3', _c2=None),
 Row(_c0='ZABU', _c1='AT 4', _c2=None),
 Row(_c0='ZABU', _c1='AT 5', _c2=None),
 Row(_c0='ZABU', _c1='ASM 104', _c2=None),
 Row(_c0='ZABU', _c1='ASM 103', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 1', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 7', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 18', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 31', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 32', _c2=None),
 Row(_c0='ZABU', _c1='N 14', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 12', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 13', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 14', _c2=None),
 Row(_c0='ZABU', _c1='H2 109', _c2=None),
 Row(_c0='ZABU', _c1='H2 110', _c2=None),
 Row(_c0='ZABU', _c1='M/TU 104', _c2=None),
 Row(_c0='ZABU', _c1='SENSM 15', _c2=None),
 Row(_c0='ZABU', _c1='H2 454', _c2=None),
 Row(_c0='ZABU', _c1='M/TIO 16', _c2=None),
 Row(_c0='ZABU', _c1='IMSVS 2/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 14/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 15/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 16/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 17/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 18/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 19/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 21/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 22/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 23/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 24/2', _c2=None),
 Row(_c0='ZABU', _c1='AT 11', _c2=None),
 Row(_c0='ZABU', _c1='ASM 58', _c2=None),
 Row(_c0='ZABU', _c1='M/SH 19', _c2=None),
 Row(_c0='ZABU', _c1='AT 1', _c2=None),
 Row(_c0='ZABU', _c1='AT 6', _c2=None),
 Row(_c0='ZABU', _c1='AT 7', _c2=None),
 Row(_c0='ZABU', _c1='SVT 1', _c2=None),
 Row(_c0='ZABU', _c1='AT 9', _c2=None),
 Row(_c0='ZABU', _c1='AT 8', _c2=None),
 Row(_c0='ZABU', _c1='AT 10', _c2=None),
 Row(_c0='ZABU', _c1='AT 13', _c2=None),
 Row(_c0='ZABU', _c1='AT 15', _c2=None),
 Row(_c0='ZABU', _c1='AT 16', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 1', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 2', _c2=None),
 Row(_c0='ZABU', _c1='M/TU 19', _c2=None),
 Row(_c0='ZABU', _c1='SVT 6', _c2=None),
 Row(_c0='ZABU', _c1='SVT 7', _c2=None),
 Row(_c0='ZABU', _c1='SVT 7/3', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 6', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 7', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 8', _c2=None),
 Row(_c0='ZABU', _c1='SVT 8', _c2=None),
 Row(_c0='ZABU', _c1='SVT 9', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 9', _c2=None),
 Row(_c0='ZABU', _c1='SVT 10', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 10', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 11', _c2=None),
 Row(_c0='ZABU', _c1='SVT 11', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 12', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 13', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 14', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 15', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 16', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 17', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 18', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 19', _c2=None),
 Row(_c0='ZABU', _c1='KZ2 20', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 1', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 3', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 4', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 5', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 6', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 7', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 8', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 9', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 10', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 13', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 14', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 15', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 16', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 17', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 18', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 19', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 20', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 21', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 25/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 26/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 23', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 24', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 25', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 26', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 27', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 30', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 34', _c2=None),
 Row(_c0='ZABU', _c1='M/CP 16/4', _c2=None),
 Row(_c0='ZABU', _c1='KZGN', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 2', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 5', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 15', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 9', _c2=None),
 Row(_c0='ZABU', _c1='KZ4 14/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 22', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 11/2', _c2=None),
 Row(_c0='ZABU', _c1='KZ3 12/2', _c2=None)]